"""Modify nullable tt_matthuoc

Revision ID: 0b4ca04b918f
Revises: 22276fef4fe4
Create Date: 2025-06-20 15:01:13.512960

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0b4ca04b918f'
down_revision = '22276fef4fe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('benh', schema=None) as batch_op:
        batch_op.alter_column('tt_matthuoc',
               existing_type=mysql.VARCHAR(length=12),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('benh', schema=None) as batch_op:
        batch_op.alter_column('tt_matthuoc',
               existing_type=mysql.VARCHAR(length=12),
               nullable=False)

    # ### end Alembic commands ###
