"""modify length data cho ketqya

Revision ID: 0d4b5f1a6743
Revises: ecf8e7ab821f
Create Date: 2025-08-17 23:10:00.038773

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0d4b5f1a6743'
down_revision = 'ecf8e7ab821f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ket_qua', schema=None) as batch_op:
        batch_op.alter_column('kq_ketqua',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=1024),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ket_qua', schema=None) as batch_op:
        batch_op.alter_column('kq_ketqua',
               existing_type=sa.String(length=1024),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###
