"""Modify pk_trangthai column

Revision ID: 1814b9199a64
Revises: c562887b5a8d
Create Date: 2025-07-28 02:01:23.115888

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1814b9199a64'
down_revision = 'c562887b5a8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phieu_kham', schema=None) as batch_op:
        batch_op.alter_column('pk_trangthai',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=20),
               comment='Trạng thái phiếu khám',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phieu_kham', schema=None) as batch_op:
        batch_op.alter_column('pk_trangthai',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=10),
               comment=None,
               existing_comment='Trạng thái phiếu khám',
               existing_nullable=True)

    # ### end Alembic commands ###
