"""Modify tt_matthuoc length

Revision ID: 22276fef4fe4
Revises: 9e51337b03df
Create Date: 2025-06-20 14:28:47.830597

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '22276fef4fe4'
down_revision = '9e51337b03df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('benh', schema=None) as batch_op:
        batch_op.alter_column('tt_matthuoc',
               existing_type=mysql.VARCHAR(length=8),
               type_=sa.String(length=12),
               existing_nullable=False)

    with op.batch_alter_table('chi_tiet_toa_thuoc', schema=None) as batch_op:
        batch_op.alter_column('tt_matthuoc',
               existing_type=mysql.VARCHAR(length=8),
               type_=sa.String(length=12),
               existing_nullable=False)
        batch_op.alter_column('thuoc_ma',
               existing_type=mysql.VARCHAR(length=8),
               type_=sa.String(length=12),
               existing_nullable=False)

    with op.batch_alter_table('phieu_kham', schema=None) as batch_op:
        batch_op.alter_column('tt_matthuoc',
               existing_type=mysql.VARCHAR(length=8),
               type_=sa.String(length=12),
               existing_nullable=True)

    with op.batch_alter_table('toa_thuoc', schema=None) as batch_op:
        batch_op.alter_column('tt_matthuoc',
               existing_type=mysql.VARCHAR(length=8),
               type_=sa.String(length=12),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('toa_thuoc', schema=None) as batch_op:
        batch_op.alter_column('tt_matthuoc',
               existing_type=sa.String(length=12),
               type_=mysql.VARCHAR(length=8),
               existing_nullable=False)

    with op.batch_alter_table('phieu_kham', schema=None) as batch_op:
        batch_op.alter_column('tt_matthuoc',
               existing_type=sa.String(length=12),
               type_=mysql.VARCHAR(length=8),
               existing_nullable=True)

    with op.batch_alter_table('chi_tiet_toa_thuoc', schema=None) as batch_op:
        batch_op.alter_column('thuoc_ma',
               existing_type=sa.String(length=12),
               type_=mysql.VARCHAR(length=8),
               existing_nullable=False)
        batch_op.alter_column('tt_matthuoc',
               existing_type=sa.String(length=12),
               type_=mysql.VARCHAR(length=8),
               existing_nullable=False)

    with op.batch_alter_table('benh', schema=None) as batch_op:
        batch_op.alter_column('tt_matthuoc',
               existing_type=sa.String(length=12),
               type_=mysql.VARCHAR(length=8),
               existing_nullable=False)

    # ### end Alembic commands ###
