"""add column ph_gioketthuc

Revision ID: 225994fd89f0
Revises: f40e18307a9c
Create Date: 2025-05-20 03:15:03.142280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '225994fd89f0'
down_revision = 'f40e18307a9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phieu_hen', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ph_gioketthuc', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phieu_hen', schema=None) as batch_op:
        batch_op.drop_column('ph_gioketthuc')

    # ### end Alembic commands ###
