"""thêm thuộc tính cho benh nhan

Revision ID: 25c3ce986391
Revises: 8e0af331856f
Create Date: 2025-08-09 14:06:26.443954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25c3ce986391'
down_revision = '8e0af331856f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('benh_nhan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bn_password', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('bn_cccd', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint(None, ['bn_cccd'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('benh_nhan', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('bn_cccd')
        batch_op.drop_column('bn_password')

    # ### end Alembic commands ###
