"""fix primary key for chandoan

Revision ID: 324345d0997e
Revises: b83e77a17b76
Create Date: 2025-06-24 16:09:22.917342

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '324345d0997e'
down_revision = 'b83e77a17b76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chan_doan')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chan_doan',
    sa.Column('tt_matthuoc', mysql.VARCHAR(length=13), nullable=False),
    sa.Column('b_ma', mysql.VARCHAR(length=10), nullable=False),
    sa.ForeignKeyConstraint(['b_ma'], ['benh.b_ma'], name='chan_doan_ibfk_3', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tt_matthuoc'], ['toa_thuoc.tt_matthuoc'], name='chan_doan_ibfk_2', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('tt_matthuoc'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
