"""fix relationship toa_thuoc and Benh v4

Revision ID: 3a5050f5acce
Revises: 88d775938349
Create Date: 2025-06-21 18:08:22.188363

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3a5050f5acce'
down_revision = '88d775938349'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chan_doan', schema=None) as batch_op:
        batch_op.drop_constraint('chan_doan_ibfk_1', type_='foreignkey')
        batch_op.drop_column('b_ten')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chan_doan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('b_ten', mysql.VARCHAR(length=100), nullable=False))
        batch_op.create_foreign_key('chan_doan_ibfk_1', 'benh', ['b_ten'], ['b_ten'], onupdate='RESTRICT', ondelete='RESTRICT')

    # ### end Alembic commands ###
