"""fix relationship toa_thuoc and Benh v5

Revision ID: 4b5f1bcd0c34
Revises: 3a5050f5acce
Create Date: 2025-06-21 18:10:45.659183

"""
from alembic import op
from flask.cli import F
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4b5f1bcd0c34'
down_revision = '3a5050f5acce'
branch_labels = None
depends_on = None


def upgrade():
    op.drop_constraint(constraint_name="PRIMARY", table_name="benh", type_="primary")
    
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('benh', schema=None) as batch_op:
        
        batch_op.alter_column('b_ten',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=1024),
               nullable=False)

    # ### end Alembic commands ###
    op.create_primary_key("pk_benh", "benh", ["b_ma"])



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('benh', schema=None) as batch_op:
        batch_op.alter_column('b_ten',
               existing_type=sa.String(length=1024),
               type_=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('b_ma')

    # ### end Alembic commands ###
