"""Add column PCD_NGAY and PCD_GIO for PhieuCDDVYT

Revision ID: 68f43a9fdf54
Revises: eb120ba465d3
Create Date: 2025-05-29 22:39:18.016038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68f43a9fdf54'
down_revision = 'eb120ba465d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phieu_cd_dvyt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pcd_ngay', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('pcd_gio', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phieu_cd_dvyt', schema=None) as batch_op:
        batch_op.drop_column('pcd_gio')
        batch_op.drop_column('pcd_ngay')

    # ### end Alembic commands ###
