"""fix primary key for chandoan v1

Revision ID: 6976d14be6b6
Revises: 324345d0997e
Create Date: 2025-06-24 16:09:59.641107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6976d14be6b6'
down_revision = '324345d0997e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chan_doan',
    sa.Column('tt_matthuoc', sa.String(length=13), nullable=False),
    sa.Column('b_ma', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['b_ma'], ['benh.b_ma'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tt_matthuoc'], ['toa_thuoc.tt_matthuoc'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('tt_matthuoc', 'b_ma')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chan_doan')
    # ### end Alembic commands ###
