"""modify data length tt_matthuoc

Revision ID: 8415c1a74f4e
Revises: fbed683e9221
Create Date: 2025-06-24 15:46:04.461263

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8415c1a74f4e'
down_revision = 'fbed683e9221'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('toa_thuoc', schema=None) as batch_op:
        batch_op.alter_column('tt_matthuoc',
               existing_type=mysql.VARCHAR(length=12),
               type_=sa.String(length=13),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('toa_thuoc', schema=None) as batch_op:
        batch_op.alter_column('tt_matthuoc',
               existing_type=sa.String(length=13),
               type_=mysql.VARCHAR(length=12),
               existing_nullable=False)

    # ### end Alembic commands ###
