"""fix relationship toa_thuoc and Benh v2

Revision ID: 88d775938349
Revises: 93ed46e20e6c
Create Date: 2025-06-21 17:39:54.835294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88d775938349'
down_revision = '93ed46e20e6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chan_doan',
    sa.Column('tt_matthuoc', sa.String(length=8), nullable=False),
    sa.Column('b_ten', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['b_ten'], ['benh.b_ten'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tt_matthuoc'], ['toa_thuoc.tt_matthuoc'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('tt_matthuoc', 'b_ten')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chan_doan')
    # ### end Alembic commands ###
