"""Thêm thuộc tính sinh hiệu vào phiếu khám

Revision ID: 8e0af331856f
Revises: 1814b9199a64
Create Date: 2025-08-02 21:34:01.831666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e0af331856f'
down_revision = '1814b9199a64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phieu_kham', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pk_huyetap_tamthu', sa.Integer(), nullable=True, comment='Huyết áp tâm thu (mmHg)'))
        batch_op.add_column(sa.Column('pk_huyetap_tamtruong', sa.Integer(), nullable=True, comment='Huyết áp tâm trương (mmHg)'))
        batch_op.add_column(sa.Column('pk_nhietdo', sa.Numeric(precision=4, scale=1), nullable=True, comment='Nhiệt độ cơ thể (°C)'))
        batch_op.add_column(sa.Column('pk_nhiptim', sa.Integer(), nullable=True, comment='Nhịp tim (lần/phút)'))
        batch_op.add_column(sa.Column('pk_nhiptho', sa.Integer(), nullable=True, comment='Nhịp thở (lần/phút)'))
        batch_op.add_column(sa.Column('pk_chieucao', sa.Numeric(precision=5, scale=2), nullable=True, comment='Chiều cao (cm)'))
        batch_op.add_column(sa.Column('pk_cannang', sa.Numeric(precision=5, scale=2), nullable=True, comment='Cân nặng (kg)'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phieu_kham', schema=None) as batch_op:
        batch_op.drop_column('pk_cannang')
        batch_op.drop_column('pk_chieucao')
        batch_op.drop_column('pk_nhiptho')
        batch_op.drop_column('pk_nhiptim')
        batch_op.drop_column('pk_nhietdo')
        batch_op.drop_column('pk_huyetap_tamtruong')
        batch_op.drop_column('pk_huyetap_tamthu')

    # ### end Alembic commands ###
