"""fix relationship toa_thuoc and Benh

Revision ID: 93ed46e20e6c
Revises: 0b4ca04b918f
Create Date: 2025-06-21 17:32:34.903638

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '93ed46e20e6c'
down_revision = '0b4ca04b918f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('benh', schema=None) as batch_op:
        batch_op.drop_constraint('benh_ibfk_1', type_='foreignkey')
        batch_op.drop_column('tt_matthuoc')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('benh', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tt_matthuoc', mysql.VARCHAR(length=12), nullable=True))
        batch_op.create_foreign_key('benh_ibfk_1', 'toa_thuoc', ['tt_matthuoc'], ['tt_matthuoc'], onupdate='RESTRICT', ondelete='RESTRICT')

    # ### end Alembic commands ###
