"""remove ketqua-dvyt relatinshiop

Revision ID: abb0031ddc68
Revises: dfcd832e966e
Create Date: 2025-05-27 15:45:10.642353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abb0031ddc68'
down_revision = 'dfcd832e966e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chi_so', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dvyt_ma', sa.String(length=8), nullable=False))
        batch_op.create_foreign_key(None, 'dich_vu_y_te', ['dvyt_ma'], ['dvyt_ma'], onupdate='RESTRICT', ondelete='RESTRICT')

    with op.batch_alter_table('dich_vu_y_te', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dvyt_mota', sa.Text(), nullable=True))

    with op.batch_alter_table('ket_qua', schema=None) as batch_op:
        batch_op.drop_constraint('ket_qua_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('ket_qua_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'chi_so', ['dvyt_ma', 'cs_ma'], ['dvyt_ma', 'cs_ma'], onupdate='RESTRICT', ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ket_qua', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('ket_qua_ibfk_1', 'chi_so', ['cs_ma'], ['cs_ma'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.create_foreign_key('ket_qua_ibfk_2', 'dich_vu_y_te', ['dvyt_ma'], ['dvyt_ma'], onupdate='RESTRICT', ondelete='RESTRICT')

    with op.batch_alter_table('dich_vu_y_te', schema=None) as batch_op:
        batch_op.drop_column('dvyt_mota')

    with op.batch_alter_table('chi_so', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('dvyt_ma')

    # ### end Alembic commands ###
