"""modify data length tt_matthuoc v1"

Revision ID: b83e77a17b76
Revises: 8415c1a74f4e
Create Date: 2025-06-24 15:47:28.120001

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b83e77a17b76'
down_revision = '8415c1a74f4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chan_doan', schema=None) as batch_op:
        batch_op.alter_column('tt_matthuoc',
               existing_type=mysql.VARCHAR(length=8),
               type_=sa.String(length=13),
               existing_nullable=False)

    with op.batch_alter_table('chi_tiet_toa_thuoc', schema=None) as batch_op:
        batch_op.alter_column('tt_matthuoc',
               existing_type=mysql.VARCHAR(length=12),
               type_=sa.String(length=13),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chi_tiet_toa_thuoc', schema=None) as batch_op:
        batch_op.alter_column('tt_matthuoc',
               existing_type=sa.String(length=13),
               type_=mysql.VARCHAR(length=12),
               existing_nullable=False)

    with op.batch_alter_table('chan_doan', schema=None) as batch_op:
        batch_op.alter_column('tt_matthuoc',
               existing_type=sa.String(length=13),
               type_=mysql.VARCHAR(length=8),
               existing_nullable=False)

    # ### end Alembic commands ###
