"""add column ph_trangthai

Revision ID: c562887b5a8d
Revises: 6976d14be6b6
Create Date: 2025-07-26 15:07:21.737755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c562887b5a8d'
down_revision = '6976d14be6b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phieu_hen', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ph_trangthai', sa.String(length=20), nullable=True, comment='Trạng thái phiếu hẹn: Đang chờ, Đã xác nhận, Đã khám, Đã hủy, Không đến'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phieu_hen', schema=None) as batch_op:
        batch_op.drop_column('ph_trangthai')

    # ### end Alembic commands ###
