"""Increase bn_ma length to 8 characters

Revision ID: dfcd832e966e
Revises: 225994fd89f0
Create Date: 2025-05-20 03:27:34.168645

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dfcd832e966e'
down_revision = '225994fd89f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phieu_hen', schema=None) as batch_op:
        batch_op.alter_column('bn_ma',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.String(length=8),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phieu_hen', schema=None) as batch_op:
        batch_op.alter_column('bn_ma',
               existing_type=sa.String(length=8),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=False)

    # ### end Alembic commands ###
