"""Modify cs_mucbthuong's datatype

Revision ID: eb120ba465d3
Revises: abb0031ddc68
Create Date: 2025-05-28 17:56:34.254546

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eb120ba465d3'
down_revision = 'abb0031ddc68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chi_so', schema=None) as batch_op:
        batch_op.alter_column('cs_mucbthuong',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chi_so', schema=None) as batch_op:
        batch_op.alter_column('cs_mucbthuong',
               existing_type=sa.String(length=100),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
