"""modify lengthdata cho password cua benhnhan

Revision ID: ecf8e7ab821f
Revises: 25c3ce986391
Create Date: 2025-08-09 14:57:49.047902

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ecf8e7ab821f'
down_revision = '25c3ce986391'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('benh_nhan', schema=None) as batch_op:
        batch_op.alter_column('bn_password',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('benh_nhan', schema=None) as batch_op:
        batch_op.alter_column('bn_password',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###
