"""Init

Revision ID: f40e18307a9c
Revises: 
Create Date: 2025-05-20 00:48:35.114091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f40e18307a9c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benh_nhan',
    sa.Column('bn_ma', sa.String(length=8), nullable=False),
    sa.Column('bn_hoten', sa.String(length=1024), nullable=True),
    sa.Column('bn_ngaysinh', sa.Date(), nullable=True),
    sa.Column('bn_gioitinh', sa.String(length=10), nullable=True),
    sa.Column('bn_sdt', sa.String(length=11), nullable=True),
    sa.PrimaryKeyConstraint('bn_ma'),
    sa.UniqueConstraint('bn_sdt')
    )
    op.create_table('ca_lam_viec',
    sa.Column('clv_stt', sa.Integer(), nullable=False),
    sa.Column('clv_tgbatdau', sa.Time(), nullable=True),
    sa.Column('clv_tgkthuc', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('clv_stt')
    )
    op.create_table('chi_so',
    sa.Column('cs_ma', sa.String(length=8), nullable=False),
    sa.Column('cs_ten', sa.String(length=225), nullable=True),
    sa.Column('cs_mucbthuong', sa.Integer(), nullable=True),
    sa.Column('cs_donvi', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('cs_ma')
    )
    op.create_table('chuyen_khoa',
    sa.Column('ck_ma', sa.String(length=8), nullable=False),
    sa.Column('ck_ten', sa.String(length=100), nullable=False),
    sa.Column('ck_mota', sa.String(length=1024), nullable=False),
    sa.Column('ck_trangthai', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('ck_ma')
    )
    op.create_table('dich_vu_y_te',
    sa.Column('dvyt_ma', sa.String(length=8), nullable=False),
    sa.Column('dvyt_ten', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('dvyt_ma')
    )
    op.create_table('ngay_ap_dung',
    sa.Column('nad_ngay', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('nad_ngay')
    )
    op.create_table('ngay_lam_viec',
    sa.Column('nl_ngay', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('nl_ngay')
    )
    op.create_table('thuoc',
    sa.Column('thuoc_ma', sa.String(length=8), nullable=False),
    sa.Column('thuoc_ten', sa.String(length=1024), nullable=False),
    sa.Column('thuoc_dvt', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('thuoc_ma')
    )
    op.create_table('tiep_tan',
    sa.Column('nv_ma', sa.String(length=8), nullable=False),
    sa.Column('nv_hoten', sa.String(length=1024), nullable=False),
    sa.Column('nv_ngaysinh', sa.Date(), nullable=True),
    sa.Column('nv_gioitinh', sa.Boolean(), nullable=False),
    sa.Column('nv_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('nv_ma')
    )
    op.create_table('trieu_chung',
    sa.Column('tc_ma', sa.Integer(), nullable=False),
    sa.Column('tc_ten', sa.String(length=100), nullable=True),
    sa.Column('tc_mota', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('tc_ma')
    )
    op.create_table('bac_si',
    sa.Column('nv_ma', sa.String(length=8), nullable=False),
    sa.Column('nv_hoten', sa.String(length=1024), nullable=False),
    sa.Column('nv_ngaysinh', sa.Date(), nullable=True),
    sa.Column('nv_gioitinh', sa.Boolean(), nullable=False),
    sa.Column('nv_password', sa.String(length=255), nullable=False),
    sa.Column('bs_csdaotao', sa.String(length=1024), nullable=True),
    sa.Column('bs_bcapchuyenmon', sa.String(length=1024), nullable=True),
    sa.Column('ck_ma', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['ck_ma'], ['chuyen_khoa.ck_ma'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('nv_ma')
    )
    op.create_table('don_gia_dv',
    sa.Column('dvyt_ma', sa.String(length=8), nullable=False),
    sa.Column('nad_ngay', sa.Date(), nullable=False),
    sa.Column('dgdv_dongia', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dvyt_ma'], ['dich_vu_y_te.dvyt_ma'], ),
    sa.ForeignKeyConstraint(['nad_ngay'], ['ngay_ap_dung.nad_ngay'], ),
    sa.PrimaryKeyConstraint('dvyt_ma', 'nad_ngay')
    )
    op.create_table('phong',
    sa.Column('phong_ma', sa.String(length=3), nullable=False),
    sa.Column('ck_ma', sa.String(length=8), nullable=False),
    sa.Column('phong_mota', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['ck_ma'], ['chuyen_khoa.ck_ma'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('phong_ma')
    )
    op.create_table('dang_ky_lich_lam',
    sa.Column('nl_ngay', sa.Date(), nullable=False),
    sa.Column('clv_stt', sa.Integer(), nullable=False),
    sa.Column('nv_ma', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['clv_stt'], ['ca_lam_viec.clv_stt'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['nl_ngay'], ['ngay_lam_viec.nl_ngay'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['nv_ma'], ['bac_si.nv_ma'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('nl_ngay', 'clv_stt', 'nv_ma')
    )
    op.create_table('lich_lam_viec',
    sa.Column('clv_stt', sa.Integer(), nullable=False),
    sa.Column('nl_ngay', sa.Date(), nullable=False),
    sa.Column('phong_ma', sa.String(length=3), nullable=False),
    sa.Column('nv_ma', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['clv_stt'], ['ca_lam_viec.clv_stt'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['nl_ngay'], ['ngay_lam_viec.nl_ngay'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['nv_ma'], ['bac_si.nv_ma'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['phong_ma'], ['phong.phong_ma'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('clv_stt', 'nl_ngay', 'phong_ma')
    )
    op.create_table('phieu_hen',
    sa.Column('ph_ma', sa.String(length=8), nullable=False),
    sa.Column('bn_ma', sa.String(length=5), nullable=False),
    sa.Column('nv_ma', sa.String(length=8), nullable=False),
    sa.Column('pk_ma', sa.Integer(), nullable=True),
    sa.Column('pk_ngaykham', sa.Date(), nullable=True),
    sa.Column('ph_giohen', sa.Time(), nullable=True),
    sa.Column('ph_ngayhen', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['bn_ma'], ['benh_nhan.bn_ma'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['nv_ma'], ['bac_si.nv_ma'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ph_ma')
    )
    op.create_table('phieu_kham',
    sa.Column('pk_ma', sa.Integer(), nullable=False),
    sa.Column('pk_ngaykham', sa.Date(), nullable=False),
    sa.Column('pcd_ma', sa.String(length=10), nullable=True),
    sa.Column('tt_matthuoc', sa.String(length=8), nullable=True),
    sa.Column('ph_ma', sa.String(length=8), nullable=False),
    sa.Column('nv_ma', sa.String(length=8), nullable=False),
    sa.Column('pk_giokhamdukien', sa.Time(), nullable=True),
    sa.Column('pk_giokhamthucte', sa.Time(), nullable=True),
    sa.Column('pk_gioketthuc', sa.Time(), nullable=True),
    sa.Column('pk_trangthai', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['nv_ma'], ['tiep_tan.nv_ma'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ph_ma'], ['phieu_hen.ph_ma'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('pk_ma', 'pk_ngaykham')
    )
    op.create_table('trieu_chung_phieu_hen',
    sa.Column('tc_ma', sa.Integer(), nullable=False),
    sa.Column('ph_ma', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['ph_ma'], ['phieu_hen.ph_ma'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tc_ma'], ['trieu_chung.tc_ma'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('tc_ma', 'ph_ma')
    )
    op.create_table('phieu_cd_dvyt',
    sa.Column('pcd_ma', sa.String(length=10), nullable=False),
    sa.Column('pk_ma', sa.Integer(), nullable=False),
    sa.Column('pk_ngaykham', sa.Date(), nullable=False),
    sa.Column('pcd_tongtien', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pk_ma', 'pk_ngaykham'], ['phieu_kham.pk_ma', 'phieu_kham.pk_ngaykham'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('pcd_ma')
    )
    op.create_table('toa_thuoc',
    sa.Column('tt_matthuoc', sa.String(length=8), nullable=False),
    sa.Column('pk_ma', sa.Integer(), nullable=False),
    sa.Column('pk_ngaykham', sa.Date(), nullable=False),
    sa.Column('tt_ngayke', sa.Date(), nullable=True),
    sa.Column('tt_taikham', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['pk_ma', 'pk_ngaykham'], ['phieu_kham.pk_ma', 'phieu_kham.pk_ngaykham'], ),
    sa.PrimaryKeyConstraint('tt_matthuoc')
    )
    op.create_table('benh',
    sa.Column('b_ten', sa.String(length=100), nullable=False),
    sa.Column('tt_matthuoc', sa.String(length=8), nullable=False),
    sa.Column('b_mota', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['tt_matthuoc'], ['toa_thuoc.tt_matthuoc'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('b_ten')
    )
    op.create_table('chi_tiet_toa_thuoc',
    sa.Column('tt_matthuoc', sa.String(length=8), nullable=False),
    sa.Column('thuoc_ma', sa.String(length=8), nullable=False),
    sa.Column('cttt_soluong', sa.Integer(), nullable=True),
    sa.Column('cttt_lieuluong', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['thuoc_ma'], ['thuoc.thuoc_ma'], ),
    sa.ForeignKeyConstraint(['tt_matthuoc'], ['toa_thuoc.tt_matthuoc'], ),
    sa.PrimaryKeyConstraint('tt_matthuoc', 'thuoc_ma')
    )
    op.create_table('ket_qua',
    sa.Column('pcd_ma', sa.String(length=10), nullable=False),
    sa.Column('dvyt_ma', sa.String(length=8), nullable=False),
    sa.Column('cs_ma', sa.String(length=8), nullable=False),
    sa.Column('kq_ketqua', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['cs_ma'], ['chi_so.cs_ma'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dvyt_ma'], ['dich_vu_y_te.dvyt_ma'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pcd_ma'], ['phieu_cd_dvyt.pcd_ma'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('pcd_ma', 'dvyt_ma', 'cs_ma')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ket_qua')
    op.drop_table('chi_tiet_toa_thuoc')
    op.drop_table('benh')
    op.drop_table('toa_thuoc')
    op.drop_table('phieu_cd_dvyt')
    op.drop_table('trieu_chung_phieu_hen')
    op.drop_table('phieu_kham')
    op.drop_table('phieu_hen')
    op.drop_table('lich_lam_viec')
    op.drop_table('dang_ky_lich_lam')
    op.drop_table('phong')
    op.drop_table('don_gia_dv')
    op.drop_table('bac_si')
    op.drop_table('trieu_chung')
    op.drop_table('tiep_tan')
    op.drop_table('thuoc')
    op.drop_table('ngay_lam_viec')
    op.drop_table('ngay_ap_dung')
    op.drop_table('dich_vu_y_te')
    op.drop_table('chuyen_khoa')
    op.drop_table('chi_so')
    op.drop_table('ca_lam_viec')
    op.drop_table('benh_nhan')
    # ### end Alembic commands ###
