"""fix relationship toa_thuoc and Benh v6

Revision ID: fbed683e9221
Revises: 4b5f1bcd0c34
Create Date: 2025-06-21 18:27:13.927545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbed683e9221'
down_revision = '4b5f1bcd0c34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chan_doan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('b_ma', sa.String(length=10), nullable=False))
        batch_op.create_foreign_key(None, 'benh', ['b_ma'], ['b_ma'], onupdate='RESTRICT', ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chan_doan', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('b_ma')

    # ### end Alembic commands ###
