from .ChuyenKhoa import ChuyenKhoa  # noqa: F401
from .BacSi import BacSi  # noqa: F401
from .BenhNhan import BenhNhan  # noqa: F401
from .PhieuKham import PhieuKham  # noqa: F401
from .PhieuHen import PhieuHen  # noqa: F401
from .TiepTan import TiepTan  # noqa: F401
from .TrieuChung import TrieuChung  # noqa: F401
from .DichVuYTe import DichVuYTe  # noqa: F401
from .Thuoc import Thuoc  # noqa: F401
from .NgayApDung import NgayApDung  # noqa: F401
from .DonGiaDV import DonGiaDichVu  # noqa: F401
from .ToaThuoc import ToaThuoc  # noqa: F401
from .ChiTietToaThuoc import ChiTietToaThuoc  # noqa: F401
from .PhieuCDDVYT import PhieuCDDVYT  # noqa: F401
from .TrieuChungPhieuHen import TrieuChungPhieuHen  # noqa: F401
from .ChiSo import ChiSo  # noqa: F401
from .KetQua import KetQua  # noqa: F401
from .Phong import Phong  # noqa: F401
from .LichLamViec import LichLamViec  # noqa: F401
from .NgayLamViec import NgayLamViec  # noqa: F401
from .CaLamViec import CaLamViec  # noqa: F401
from .DangKyLichLam import DangKyLichLam  # noqa: F401
from .Benh import Benh  # noqa: F401
from .ChanDoan import ChanDoan  # noqa: F401